base_url = "https://gabe.tec.br"
title = "gabe's garden 🦦"
author = "gabe"
description = "my garden to talk about nixos, rust, golang and some another things"
default_language = "pt-BR"

compile_sass = true
build_search_index = false

generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [{ name = "tags", feed = true }]

[markdown]
base_url = "https://gabe.tec.br"

highlight_code = true
highlight_theme = "inspired-github"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
menu = [
    { name = "/now", url = "/now", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
]

social = [
    { name = "git", url = "https://github.com/ImGabe/blog", icon = "github" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
    { name = "atom", url = "/atom.xml", icon = "atom" },
]

contacts = [
    { name = "email", url = "gabrielpmonte@gmail.com" },
    { name = "github", url = "https://github.com/ImGabe" },
]

languages = [
    {name = "br",  code = "pt-BR", url = ""},
    {name = "en", code = "en", url = "en"},
]

[languages.en]
title = "gabe's garden 🦦"
description = "my garden to talk about nixos, rust, golang and some another things"

taxonomies = [{ name = "tags", feed = true }]